### ISSUE TITLE
Loop detection rewording

### ISSUE THREAD

**Issue by ghost** [fiestajetsam/draft-gruessing-ntp-ntpv5-requirements#17]
Ulrich suggests:
> Isn't it preferable to use _positive_ requirements instead of negative ones? For example: Instead of " The protocol's loop avoidance mechanisms SHOULD NOT use identifiers tied to network topology." Why not " The protocol's loop avoidance mechanisms SHOULD be able to use identifiers that change over time. "?

I'd propose rewording it to:
> The protocol's loop avoidance mechanisms MUST be able to use identifiers that change over time and are not tied to network topology

**Comment by ghost** [comment]
cc @davidv1992 as this touches your contributions and I suspect you'll have opinions about the text I've proposed in 3cd72f231b4aad3.

**Comment by davidv1992** [comment]
I see no problems in the new wording.

**Comment by ghost** [comment]
Thanks!
