### ISSUE TITLE
Time services versus network service providers

### ISSUE THREAD

**Issue by ghost** [fiestajetsam/draft-gruessing-ntp-ntpv5-requirements#37]
Ulrich writes:

> Think this section is rather confusing: " Clients SHOULD periodically re-establish connections with servers to prevent attempting to maintain connectivity to a dead host and give network operators the ability to move traffic away from hosts in a timely manner": What is the relationship between clients querying servers and network operators moving traffic?

I kinda agree, this should separate network providers from time sync providers even though they can be one and the same....

**Comment by hart-NTP** [comment]
It's not terribly common, unfortunately, for ISPs in the US to provide time service to their clients.  In my experience most folks are using pool.ntp.org, time.apple.com, time.google.com, NIST/USNO, etc.  Most ISPs focus on things that bring in revenue.  Sure, they likely use NTP themselves, and could easily provide the service to clients, but I've never run across it.  Which ISP wants to field customer support tickets about clients having trouble finding the time?
